### ISSUE TITLE
windows环境下add_executable无法生成可执行文件

### ISSUE THREAD

**Issue by pbabading** [eshoyuan/PaddleOCR_TensorRT_cpp#1]

**Comment by eshoyuan** [comment]
抱歉, 没有在windows环境下测试过.

**Comment by eshoyuan** [comment]
可以尝试先用windows跑通一个TensorRT官方的示例. 本项目依赖很少, 应该可以在windows下环境运行, 可能需要针对windows环境修改CMakeLists.

**Comment by pbabading** [comment]
TensorRT自带Sample里的MINST我已经能跑通了
就是PaddleOCR的可执行文件生成不了 很奇怪

**Comment by pbabading** [comment]
D:\PaddleOCR_TensorRT_cpp-main\build>cmake ..
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.32.31332.0
-- The CXX compiler identification is MSVC 19.32.31332.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found TensorRT: D:/ProgramData/TensorRT-7.2.1.6/lib/nvinfer.lib (found version "..")
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0 (found version "11.0")
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc15
-- OpenCV STATIC: OFF
-- Found OpenCV: D:/projects/cpp/opencv/build (found version "4.6.0")
-- Found OpenCV 4.6.0 in D:/projects/cpp/opencv/build/x64/vc15/lib
--  <span style="background-color: sandybrown">You might need to add D:\projects\cpp\opencv\build\x64\vc15\bin to your PATH to be able to run your applications.</mark>
-- Configuring done
-- Generating done
-- Build files have been written to: D:/PaddleOCR_TensorRT_cpp-main/build

这里倒数第四行提示 应该加在哪

**Comment by eshoyuan** [comment]
这个不一定会影响运行, 后面具体报错是什么

**Comment by pbabading** [comment]
![Snipaste_2022-08-04_16-17-30](https://user-images.githubusercontent.com/51269050/182799049-25d43149-e7df-40b9-a8f8-2912b9fdd078.png)

没有报错 你看截图

**Comment by eshoyuan** [comment]
那你继续输入 `make`

**Comment by pbabading** [comment]
D:\PaddleOCR_TensorRT_cpp-main\build>mingw32-make
mingw32-make: *** No targets specified and no makefile found.  Stop.

D:\PaddleOCR_TensorRT_cpp-main\build>

**Comment by eshoyuan** [comment]
你的目录下makefile文件是否存在? 如果生成的是makefile.txt之类的重命名为makefile或Makefile.

**Comment by pbabading** [comment]
![13244](https://user-images.githubusercontent.com/51269050/182801167-072c855b-7a43-49f9-b12a-0fb9e1f2e008.png)
没有诶

**Comment by eshoyuan** [comment]
https://blog.csdn.net/weixin_42660446/article/details/119650036

你可以删除build文件夹, 尝试将`cmake ..`替换为`cmake . -G "Unix Makefiles"`.

**Comment by pbabading** [comment]
D:\PaddleOCR_TensorRT_cpp-main\build>cmake . -G "Unix Makefiles"
CMake Error: The source directory "D:/PaddleOCR_TensorRT_cpp-main/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
好像也不对欸

**Comment by eshoyuan** [comment]
`cmake .. -G "Unix Makefiles"` 直接复制了没注意, 不好意思.

**Comment by pbabading** [comment]
啊哈哈 我也没发现

D:\PaddleOCR_TensorRT_cpp-main\build>
D:\PaddleOCR_TensorRT_cpp-main\build>cmake .. -G "Unix Makefiles"
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "D:/PaddleOCR_TensorRT_cpp-main/build/CMakeFiles/CMakeOutput.log".

D:\PaddleOCR_TensorRT_cpp-main\build>

**Comment by pbabading** [comment]
看了这博客感觉是选到vs的编译器了

**Comment by eshoyuan** [comment]
你搜一下安装一下MinGW.
`cmake ..`失败是因为选到MSVC了, `cmake .. -G "Unix Makefiles"`失败是你本地没有匹配的编译器.

**Comment by pbabading** [comment]
但是我已经有安装过MinGW

**Comment by eshoyuan** [comment]
有加入到环境变量吗

**Comment by pbabading** [comment]
有的 我准备卸载重新安装下试试 有可能版本太落后了

**Comment by eshoyuan** [comment]
https://stackoverflow.com/questions/70524164/cmake-c-compiler-not-set-after-enablelanguage
可以参考一下这个, 应该不是版本的问题

**Comment by eshoyuan** [comment]
> https://stackoverflow.com/questions/70524164/cmake-c-compiler-not-set-after-enablelanguage 可以参考一下这个, 应该不是版本的问题

即在cmake命令加入 -DCMAKE_CXX_COMPILER={g++路径} -DCMAKE_C_COMPILER={gcc路径}

**Comment by pbabading** [comment]
大佬 我重装也试过了  加路径也试过了 都不行。。。

**Comment by eshoyuan** [comment]
在CMakeLists里1-2行之间加呢
```
set( CMAKE_CXX_COMPILER "{c++路径}" )
set( CMAKE_C_COMPILER "{gcc路径}" )
```
路径可以参考这张图里的
![image](https://user-images.githubusercontent.com/57313880/182811624-a64b334c-6ecb-4325-8858-3c576e8ffa31.png)

**Comment by pbabading** [comment]
![1344](https://user-images.githubusercontent.com/51269050/182812236-955f03c5-7456-43b7-aee0-66bc9fb8f690.png)

**Comment by pbabading** [comment]
很遗憾还是不行 。。。。我服了我电脑了 我重启下试试

**Comment by eshoyuan** [comment]
不要{}的

**Comment by pbabading** [comment]
我去掉后又跑了下 还是不行欸

**Comment by pbabading** [comment]
![3121334](https://user-images.githubusercontent.com/51269050/182818863-2ae43ce5-ee5a-4287-ae2d-2b85751c78d4.png)
我把vs的编译器先删了 报这个 

但我cmd gcc -v能找到这个
![14344](https://user-images.githubusercontent.com/51269050/182819028-4acc7ccf-10e0-4f3c-863f-083292af269b.png)

**Comment by eshoyuan** [comment]
我不太清楚具体原因, 几点建议: 1. -G "Unix Makefiles"最好加上 2. 每次cmake前删除build文件夹 3. 可以复制报错百度/谷歌 目前看来你这个应该是编译器配置的问题, 没有类似的环境, 我这里也帮不上什么忙.

**Comment by pbabading** [comment]
好的我自己加油试试 大佬如果成功了 是不是可以tensorRT加速的

**Comment by eshoyuan** [comment]
嗯 是这样的.

**Comment by eshoyuan** [comment]
如果运行成功了, 麻烦反馈一下~

**Comment by pbabading** [comment]
好的好的

**Comment by pbabading** [comment]
大佬我终于可以生成makefile了
我把build生成的cmakeCache.txt删除后再运行cmake .. -G "Unix Makefiles"就可以了

**Comment by pbabading** [comment]
![sfdsfdsf](https://user-images.githubusercontent.com/51269050/182827328-3d9cfad7-e93a-46f3-9e1f-e180e87aa9e7.png)
但是现在出现这个opencv的问题

**Comment by eshoyuan** [comment]
opencv装了吗
![image](https://user-images.githubusercontent.com/57313880/182876591-b3d137ee-6c2b-471a-8f2a-db75008ba8ff.png)

**Comment by pbabading** [comment]
![dsfsdf](https://user-images.githubusercontent.com/51269050/182986924-f3402c79-95e8-43f6-baf3-d7322fa13100.png)
有的 我感觉有可能是因为我opencv是4.6版本

**Comment by pbabading** [comment]
![fdsfsdafa](https://user-images.githubusercontent.com/51269050/182989355-bec8043a-9ad2-48c8-ad47-df67b70e0ea9.png)
大佬 你有这个dlfcn.h文件吗 我电脑里根本没这个

**Comment by eshoyuan** [comment]
https://stackoverflow.com/questions/1397022/mingw-3-4-5-missing-dlfcn-h

**Comment by eshoyuan** [comment]
Windows的话CMake的find_package可能无法使用, 需要set命令手动设置OpenCV_INCLUDE_DIRS, OpenCV_LIBS等.

> ![sfdsfdsf](https://user-images.githubusercontent.com/51269050/182827328-3d9cfad7-e93a-46f3-9e1f-e180e87aa9e7.png) 但是现在出现这个opencv的问题

**Comment by eshoyuan** [comment]
> ![sfdsfdsf](https://user-images.githubusercontent.com/51269050/182827328-3d9cfad7-e93a-46f3-9e1f-e180e87aa9e7.png) 但是现在出现这个opencv的问题

你需要手动set路径, find_package在windows下可能没法直接用.

**Comment by eshoyuan** [comment]
推荐你使用Windows的 支持cuda的linux子系统, https://docs.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl 注意支持cuda的话需要一定满足系统版本需求.

**Comment by pbabading** [comment]
> > ![sfdsfdsf](https://user-images.githubusercontent.com/51269050/182827328-3d9cfad7-e93a-46f3-9e1f-e180e87aa9e7.png) 但是现在出现这个opencv的问题
> 
> 你需要手动set路径, find_package在windows下可能没法直接用.

这个我已经解决了

**Comment by pbabading** [comment]
> 推荐你使用Windows的 支持cuda的linux子系统, https://docs.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl 注意支持cuda的话需要一定满足系统版本需求.

我也觉得 windows上好麻烦

**Comment by pbabading** [comment]
大佬我能请教一下动态尺寸的问题吗
![image](https://user-images.githubusercontent.com/51269050/182994163-0b771b55-fb1f-4c8a-820b-e2407da5f0e4.png)
这是我在paddleocr原项目下windows c++部署时 使用tensorrt出现的问题

**Comment by eshoyuan** [comment]
这个信息太少了, 看不出什么

**Comment by pbabading** [comment]
好吧 我准备先搞下linux系统
