### ISSUE TITLE
onnx转engine对tensorrt的版本有要求吗，转换过程报错

### ISSUE THREAD

**Issue by Jarvisxize** [eshoyuan/PaddleOCR_TensorRT_cpp#2]
While parsing node number 355 [GlobalAveragePool]:
ERROR: builtin_op_importers.cpp:1087 In function importGlobalAveragePool:
[8] Assertion failed: !isDynamic(kernelSize) && "Cannot run global average pool on an input with dynamic spatial dimensions!"

**Comment by eshoyuan** [comment]
这是data目录下提供的onnx吗

**Comment by Jarvisxize** [comment]
是的

**Comment by Jarvisxize** [comment]
![image](https://user-images.githubusercontent.com/40790949/183011394-2e7433ec-7d11-4b72-bd05-ea6c2f663cbb.png)
项目编译有这个问题

**Comment by eshoyuan** [comment]
你的TRT版本是什么

**Comment by eshoyuan** [comment]
https://forums.developer.nvidia.com/t/tensorrt-inference-unstable-compared-onnxruntime/176483/4 不知道这个是否有帮助

**Comment by Jarvisxize** [comment]
感谢您抽空来做解答，我的版本是7.0.0.11
