### ISSUE TITLE
请教一下 一次识别多张图片怎么设置吗

### ISSUE THREAD

**Issue by pbabading** [eshoyuan/PaddleOCR_TensorRT_cpp#4]

**Comment by eshoyuan** [comment]
PPOCR可以支持batch size != 1的情况, 我出于我的业务场景本项目写死了batch size = 1, 可以根据readme中的参考资料进行修改.

**Comment by eshoyuan** [comment]
https://github.com/zwenyuan1/PaddleOCRv2_TensorRT 和官方源码
