### ISSUE TITLE
结果为nan

### ISSUE THREAD

**Issue by wangzhenlin123** [eshoyuan/PaddleOCR_TensorRT_cpp#5]
你好，我换了其他的图，但是输出结果为：score: -nan(ind) ，请问是什么原因呢

`Searching for engine file with name: trt.engine.822e5c5577378bdc5070023afe007ffc.fp16.1.1.40000000000
Engine found, not regenerating...
0
        score: -nan(ind)
Success! Inference time: 4 ms, for batch size of: 1`

**Comment by eshoyuan** [comment]
请问是什么模型

**Comment by wangzhenlin123** [comment]
用您默认的模型：modelv3.onnx

**Comment by eshoyuan** [comment]
请注意main.cpp的84行`score /= count;`, 你出现了nan是因为这里count为0, 也就是说, 从你的图中没有识别出任何有效字符, 建议你换张图或重新训练模型

**Comment by wangzhenlin123** [comment]
我换了很多图了，都是简单的字符，一个也没识别出来，请问这对字符或者图有什么讲究细节要求吗

**Comment by eshoyuan** [comment]
可以发出来看看

**Comment by wangzhenlin123** [comment]
方便您加我vx嘛：15515650363

**Comment by eshoyuan** [comment]
可以就发在这里

**Comment by eshoyuan** [comment]
> 可以就发在这里

如果涉及保密问题, 可以发到我邮箱: eshoyuan@gmail.com

**Comment by wangzhenlin123** [comment]
![5](https://user-images.githubusercontent.com/51401216/186619352-fe908324-23b8-4301-955c-8bdc62840274.png)
![3](https://user-images.githubusercontent.com/51401216/186619512-b422e4d7-5f99-4fb7-9c64-e552f1b7cdfb.png)
![2](https://user-images.githubusercontent.com/51401216/186619551-2ba062bc-9c97-47a1-b0c0-bb506b86e14b.png)
不涉密，我也是随便找的，只不过不知道git的发图方式

**Comment by eshoyuan** [comment]
确实不应该, 挺奇怪的

**Comment by wangzhenlin123** [comment]
我不是做ocr的，这个对输入的宽和高比例有限制要求吗

**Comment by eshoyuan** [comment]
输入会自动resize, 只要不是长宽比特别夸张的都没有问题 (比如文本长度为30的话resize完全挤在一起了)

**Comment by wangzhenlin123** [comment]
那长宽比大概多大区间比较合适呢

**Comment by eshoyuan** [comment]
预训练模型是在48,320上训练的 (即最大的长宽比不要超过320:48太多就行了), 如果长文本的话需要重新训练.

**Comment by wangzhenlin123** [comment]
你好请问，识别不准确现在这个原因找到了吗？

**Comment by eshoyuan** [comment]
没有欸
