### ISSUE TITLE
onnx ocr, how to show multiple candidates during inference? steve8000818@gmail.com

### ISSUE THREAD

**Issue by nissansz** [eshoyuan/PaddleOCR_TensorRT_cpp#6]
onnx ocr, how to show multiple candidates during inference? steve8000818@gmail.com

**Comment by eshoyuan** [comment]
Do you mean that you want to get possible candidate score like image classification?

**Comment by nissansz** [comment]
No. Need several best matches.
1. 0.99
2. 0.95 etc.

**Comment by eshoyuan** [comment]
It's difficult to implement since the use of CTC decode. You can read some references or my code to learn how to do CTC decode during inference. We can design a algorighm to meet your requirements definitely, but I don't know anyone has implemented it.

**Comment by nissansz** [comment]
Thank you. What is the best accuracy you get from PaddleOcr?

**Comment by eshoyuan** [comment]
You can check PaddleOCR document. This repository is about deploying PaddleOCR.

**Comment by eshoyuan** [comment]
This blog https://distill.pub/2017/ctc/ illustrates CTC decode well. I hope this can help you.

**Comment by nissansz** [comment]
Thank you. It is hard for me to understand the principle.
